version: 2

jobs:
  build:
    working_directory: .
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install libhunspell-dev
      - run: tox
